node_js:
- "0.10"
script: node node_modules/intern/runner.js config=tests/intern
language: node_js
install:
  - npm install
  - npm install -g grunt-cli
  - wget https://api.equinox.io/1/Applications/ap_pJSFC5wQYkAyI0FIVwKYs9h1hW/Updates/Asset/ngrok.zip\?os\=linux\&arch\=386\&channel\=stable
  - unzip ./ngrok.zip\?os=linux\&arch=386\&channel=stable
before_script:
  - node tests/integration/request_recorder.js &

  # Create a random ngrok subdomain
  - export SUBDOMAIN=$RANDOM$RANDOM
  - ./ngrok -authtoken $NGROK_AUTH -subdomain $SUBDOMAIN -log=stdout 8500 > /dev/null &
script:
  - grunt travis
after_script:
  - cat ./tracker.log
env:
  global:
  - secure: "Ort7jy0HpYi0EGfuRYGW4tawmVJzfUUNXhtJEOWR09FYL28XUyxvjUnpS1WZlD0/rBZiuDPBep1Tc81F88pSns4ZAg1lxlM/zheWrCKvYudeAia2g06OqOA1JfeVWX7TjemJ5s1lY66b5VQrDG1QLIO1RPjgWWea0MpSQzv00Ms="
  - secure: "JFprkMXxrQZhRlYvJb+ZOr540QuzMU2jQtf39oPzg8uqcV5TDDWTuUZ6D3ogyNJnzH0mYDRzHZQEAqxkyjfndpIgN+a+dBM1l4WoKrTR9BpA3ZZD6zFEG7UrHBcvZgvopbY1wMPXbn4JL7J7SPPOjvvrjjIk/QIsTUYft/UOyXI="

  # NGROK_AUTH token
  - secure: "aLAryygcpImMFo2ZrDhcrE5IFGrt300BfCXu4r2mChoGUMUU6fJltfKktwv9OKsfWFhhJ44fpJX2nSmGmOyGDljC8eegXUjB0vToQ0/NGvtibE+ug/T4fbMgVMA842Y1MB9MvIK10/cD2/2bLKGYHrNq8196YxBVptvVLu+aphY="
