name: Build

on:
  push:
    branches:
      - '**' # Prevents builds on tag

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: pnpm cache
        uses: actions/cache@v2
        with:
          path: ./common/temp/pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('common/config/rush/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-

      - name: Install
        run: node common/scripts/install-run-rush.js install

      - name: Build
        run: node common/scripts/install-run-rush.js rebuild --verbose

      - name: Test
        run: node common/scripts/install-run-rush.js test --verbose

      - name: Block Concurrent Executions of E2E Tests
        if: ${{ env.SAUCE_ACCESS_KEY != '' }}
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 20
          same-branch-only: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Host for Saucelabs Tunnel
        if: ${{ env.SAUCE_ACCESS_KEY != '' }}
        run: echo "127.0.0.1 snowplow-js-tracker.local" | sudo tee -a /etc/hosts

      - name: Run End to End Tests
        if: ${{ env.SAUCE_ACCESS_KEY != '' }}
        working-directory: ./trackers/browser-tracker
        run: node ../../common/scripts/install-run-rushx.js test:e2e:sauce

      - name: Upload sp.js artifact
        uses: actions/upload-artifact@v2
        with:
          name: sp.js
          path: trackers/browser-tracker/dist/sp.js
